#!/bin/env bash
# generate one priv file only
# e.g. "./genonly md-priv/2024-06-27-16.md"

file="$1"

set -e

mkdir -p pub/priv

rm -f res/diag/*
mkdir -p res/diag

cp index.md pub/priv/index.md
printf "\n\n" >>pub/priv/index.md

export MERMAID_FILTER_FORMAT="svg"
export MERMAID_FILTER_THEME="dark"
export MERMAID_FILTER_BACKGROUND="transparent"
export MERMAID_FILTER_LOC="res/diag"
export MERMAID_FILTER_IMAGE_CLASS="mermaid"

ARGS="-A common.html -F mermaid-filter --toc --css style.css -t html -s --citeproc --bibliography=bib.bib --biblatex -L ./server-katex/filter.lua"
NHEAD=13

priv_words=0
priv_count=0
EXTRA="-A append.html"
plot="$(head -n$NHEAD "$file" | grep -m 1 plot | cut -c 7-)"
[[ "$plot" = "true" ]] && EXTRA="$EXTRA -A plot.html"

name="$(basename $file | cut -f 1 -d '.')"
pandoc $ARGS $EXTRA "$file" -o "pub/priv/$name".html &
title="$(head -n$NHEAD "$file" | grep -m 1 ^title | cut -c 8-)"
date="$(echo $name | rev | cut -c 4- | rev)"
pubdate="$(head -n$NHEAD "$file" | grep -m 1 ^date | cut -c 6-)"
author="$(head -n$NHEAD "$file" | grep -m 1 ^author | cut -c 8-)"
count="$(pandoc --lua-filter wordcount.lua "$file")"
priv_words=$((priv_words + count))
priv_count=$((priv_count + 1))
# echo "- [$title]($name.html) $date - $pubdate · $count words · $author" >>pub/priv/index.md
echo "- [$title]($name.html) $pubdate · $count words · $author" >>pub/priv/index.md
echo "generated $title"

echo "waiting..."
for job in $(jobs -p); do
	wait "$job" || echo "$job failed"
done

cp *.css pub/priv/
cp -r res/ pub/priv/

echo "done!"
