#!/bin/sh

echo "Are you sure? Make sure you finished all your TODOs first!"

export DATE=$(date '+%Y-%m-%d')

name=$(date '+%Y-%m-%d-%H')
cp -i template.md md-priv/"$name".md

envsubst <md-priv/"$name".md >md-priv/tmp
mv md-priv/tmp md-priv/"$name".md

echo md-priv/"$name".md
